version: "3"

services:
  ui:
   build:
      context: ./client
      dockerfile: Dockerfile
   ports:
    -  3000:3000
   container_name: mern-client
   networks:
    -  mern-stack-net
   depends_on:
    - api
  #  stdin_open: true
   tty: true

  api:
   build:
      context: ./server
      dockerfile: Dockerfile
   ports:
     - 4000:4000
   container_name: mern-api
   env_file:
    - ./server/.env
   networks:
     - mern-stack-net

networks:
  mern-stack-net:
    driver: bridge